# Generated by Django 3.2.11 on 2022-11-03 10:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='others_field',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
