# Generated by Django 3.2.11 on 2022-11-03 20:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='event name')),
                ('eventcode', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='event code')),
                ('event_type', models.CharField(choices=[('birthday', 'birthday'), ('wedding', 'wedding'), ('anniversary', 'anniversary'), ('farewell', 'farewell'), ('other', 'other')], default='other', max_length=20, verbose_name='event_type')),
                ('location', models.TextField(max_length=200)),
                ('gmap_link', models.URLField(blank=True, null=True)),
                ('contact_person_name', models.CharField(max_length=50)),
                ('contact_person_phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None)),
                ('banner_image', models.ImageField(upload_to='', verbose_name='banner image')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('rsvp_code', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
                ('has_website', models.BooleanField(default=True)),
                ('has_gallery', models.BooleanField(default=True)),
                ('has_schedule', models.BooleanField(default=False)),
                ('has_wishes', models.BooleanField(default=False)),
                ('others_field', jsonfield.fields.JSONField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('hosts', models.ManyToManyField(related_name='hosted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
