# Generated by Django 3.2.11 on 2022-11-03 21:00

from django.db import migrations
import jsonfield.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_person_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='others_field',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
