# Generated by Django 3.2.11 on 2022-11-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20221104_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='banner image'),
        ),
    ]
