# Generated by Django 3.2.11 on 2022-11-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(default='/profile_default.png', upload_to='', verbose_name='banner image'),
        ),
    ]
