# Generated by Django 3.2.11 on 2022-11-04 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_alter_event_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Invitee name')),
                ('invitee_phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254, verbose_name='Invitee email address')),
                ('rsvp_status', models.CharField(choices=[('N/A', 'N/A'), ('yes', 'yes'), ('no', 'no')], default='N/A', max_length=5, verbose_name='RSVP response')),
                ('invite_medium', models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Email', 'Email'), ('Unknown', 'Unknown')], default='Unknown', max_length=15, verbose_name='Invite sent via')),
                ('rsvp_message', models.TextField(max_length=200)),
                ('max_guest_count', models.PositiveSmallIntegerField()),
                ('guest_count', models.PositiveSmallIntegerField()),
                ('others', jsonfield.fields.JSONField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_event', to='events.event')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_for', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
