# Generated by Django 3.2.11 on 2022-11-07 13:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20221107_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='80fae0ef-4617-425c-88ee-02b5bd84a549', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitee',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='80fae0ef-4617-425c-88ee-02b5bd84a549', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
