# Generated by Django 3.2.11 on 2022-11-07 14:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20221107_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitee',
            name='slug',
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='eventcode', unique=True),
        ),
    ]
