# Generated by Django 3.2.11 on 2022-11-07 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitee',
            name='rsvp_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitee',
            name='sent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
