# Generated by Django 3.2.11 on 2022-11-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20221108_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='max_guest_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
