# Generated by Django 3.2.11 on 2022-11-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_invitee_max_guest_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
