# Generated by Django 3.2.11 on 2022-11-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20221111_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='invite_medium',
            field=models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Email', 'Email'), ('RSVP_code', 'RSVP_code'), ('Unknown', 'Unknown')], default='Unknown', max_length=15, verbose_name='Invite sent via'),
        ),
    ]
