# Generated by Django 3.2.11 on 2022-11-23 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_auto_20221123_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likers_of_media', to=settings.AUTH_USER_MODEL),
        ),
    ]
