# Generated by Django 3.2.11 on 2022-11-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20221124_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='file_count',
        ),
    ]
