# Generated by Django 3.2.11 on 2022-11-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_album_file_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
