# Generated by Django 3.2.11 on 2022-11-28 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0019_media_is_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wish_message', models.TextField(max_length=500)),
                ('wish_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Wish by Line')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Optional image for Wish')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='Optional video for Wish')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_video', models.BooleanField(default=None, null=True)),
                ('others', jsonfield.fields.JSONField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_event', to='events.event')),
                ('wisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_madeby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
