# Generated by Django 3.2.11 on 2022-11-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20221128_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='image',
            new_name='wish_image',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='video',
            new_name='wish_video',
        ),
    ]
