# Generated by Django 3.2.11 on 2022-11-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20221128_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
