# Generated by Django 3.2.11 on 2022-11-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_wish_is_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='is_video',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
